default: &default
  adapter: postgresql
  encoding: unicode
  username: izebiafe
  password: <%= ENV['PG_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Budgetapp_development

test:
  <<: *default
  database: Budgetapp_test

production:
  <<: *default
  database: <%= ENV['PG_DATABASE'] %>
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: require
